### ISSUE TITLE
Timewarp Bug

### ISSUE THREAD

**Issue by MrMeeb** [Sigma88/Sigma-Dimensions#11]
It is not possible to on-rails timewarp even above 180km, due to the ship being under pseudo acceleration. 

![image](https://cloud.githubusercontent.com/assets/16963756/13761125/ac3f1bf8-ea2e-11e5-885f-34dc6e7f662e.png)

**Comment by Sigma88** [comment]
I've tried to solve this issue with commit 0c76a5909402ec9cb8ffc35004da6d8f29cb5da9

could you try to reproduce the issue with the [dev.version](https://github.com/Sigma88/Sigma-Dimensions/archive/Development.zip) and let me know if it fixes it?

**Comment by Sigma88** [comment]
this issue was solved by https://github.com/Sigma88/Sigma-Dimensions/commit/0c76a5909402ec9cb8ffc35004da6d8f29cb5da9
