### ISSUE TITLE
ScanSat compatibility

### ISSUE THREAD

**Issue by Sigma88** [Sigma88/Sigma-Dimensions#12]
Requested by: [Armageddon](http://forum.kerbalspaceprogram.com/index.php?/topic/126548-wip-sigma-dimensions/&page=16#comment-2456096)

Link to the mod: [ScanSat](https://github.com/S-C-A-N/SCANsat)

**Comment by armegeddon** [comment]
You are grabbing the resize varaible from SigmaBinary instead of SigmaDimensions, so doesn't work.

**Comment by armegeddon** [comment]
Also, ModuleSCANresourceScanner should have ,* after it because some parts uses multiple resource scanners on a single part, particularly DMagicOrbitaScience

**Comment by Sigma88** [comment]
@armegeddon 
when using
@MODULE**:HAS[#name[ModuleSCANresourceScanner]]**
instead of
@MODULE**[ModuleSCANresourceScanner]**

the patch will apply to all modules with that name and not only the first one (like in the second case)

**Comment by Sigma88** [comment]
this issue was solved, will be included in next release
