### ISSUE TITLE
KSP 1.1.3 hangs on load with sigma dimensions and certain planet packs.

### ISSUE THREAD

**Issue by sentania** [Sigma88/Sigma-Dimensions#18]
When loading sigma dimensions and KSP 1.1.3 and stock (rescaled for 6.4k) - everything loads normally.

When loading with all the planet packs of my install KSP hangs - with logs spews from sig dimensions and has template eeloo.

Some planet packs are not affected - OPM, trans-keptunian, PluronKhato.  I haven't spent the exact time to determine which ones are affected, and which ones are not.  

However I was able to replicate the hang by adding KDS (Kumar's Dwarf Planets) to the install.

I have attached a zip with the working "stock install" - Rescale config, Squad, MM, and Kopernicus, OPM+TK+PK, and with a hang situtation.

**Comment by sentania** [comment]
[sigdimensions.zip](https://github.com/Sigma88/Sigma-Dimensions/files/362863/sigdimensions.zip)


attachment

**Comment by Sigma88** [comment]
from a first look all I can say is that since your "big verse" did not contain KDS there might be 2 different issues.
does KDS hang on eeloo as well?

**Comment by Sigma88** [comment]
I've looked at the logs for your verse and there is nothing that could explain the issue.
I will need some more time to find out what is going wrong

**Comment by Sigma88** [comment]
I've notified protojeb [here](http://forum.kerbalspaceprogram.com/index.php?/topic/139245-113-kopernicus-kumars-dwarf-stars-v02-26jun16/&do=findComment&comment=2675629)

**Comment by sentania** [comment]
Sorry I inadvertantly left KDS out of the mix, that obviously confused things.

I've attached another bundle of logs.  When I fixed KDS as you describe above, the game logs, but logs a bunch of errors for Sigma Dimensions.

I've attached logs with stock + SD, stock+SD+FixedKDS, and my full install with SD, full w/ SD + fixed KDS, and the full install w/o sigma dimensions.

[SigDimensionslogs.zip](https://github.com/Sigma88/Sigma-Dimensions/files/363759/SigDimensionslogs.zip)

**Comment by Sigma88** [comment]
I'm going to bet there are other typos on KDS, protojeb has an history of messing up brackets -.-

**Comment by sentania** [comment]
More data:

The follow mods when added to a KSP install with nothing but Kopernicus and Sigmensions load, but lots of various errors:
Keridani Star System
Interstellar Adventure Revived
KDS ("fixed") - hangs with the eeloo spam if "unfixed"
Antares

This load without issues - collectively, and individually:
Arkas
Extrasolar
KerbolOrigins
Kronkus
Larinax
OPM
Otherworlds
Saru
Sentar
Sido Urania
PluronKhato
Trans-Keptunian
XPC (all of them)

I found by taking dropping antares into the collective working list above - it would hang with the aforementioned eeloo spam.

I'll go do my best to ping the broken mod authors on the forum that they don't work with your stuff :)

**Comment by Sigma88** [comment]
ok so unless there is an actual SD issue here I will close the issue :D
let me know if you have found anything that can be linked to SD
