### ISSUE TITLE
atmoTopLayer seems to be reapplied on every reload

### ISSUE THREAD

**Issue by infoman** [Sigma88/Sigma-Dimensions#31]
When I quit to main menu and reload, it seems to be applying that atmoTopLayer thing all over again. Here's what it looks like after 4 and 5 reloads with the following settings (based on original KScale64 and improved for the latest SigDim version):

```
SigmaDimensions
{
	// Base Settings

	Resize = 6.4
	Rescale = 6.4
	Atmosphere = 1.33
	dayLengthMultiplier = 4


	// Advanced Settings

	landscape = .50
	geeASLmultiplier = 1

	resizeScatter = 1
	resizeBuildings = 2

	CustomSoISize = 0
	CustomRingSize = 0

	atmoASL = 1
	tempASL = 1
	atmoTopLayer = 1.4
	atmoVisualEffect = 1

	scanAltitude = 1
}
```
![baaad-atmo](https://cloud.githubusercontent.com/assets/74520/21077195/5cf53f40-bf54-11e6-9dc8-08eac324b373.png)

This makes things difficult and requires the full game restart to make everything work properly again.

**Comment by Sigma88** [comment]
thanks for the report
It's an easy fix but I have another more difficult bug that is slowing the update.
