### ISSUE TITLE
Add Textures to Kittopia Exports

### ISSUE THREAD

**Issue by Sigma88** [Sigma88/Sigma-Dimensions#33]
@GregroxMun proposed on #Kopernicus to add textures to the kittopia exports.

While I think this is a good idea I don't think SD is the right repository to dump all that data on

@StollD do you think a new repository could be added to the Kopernicus organization to hold all Kittopia Exports? (cfgs and textures)

yes? no? bad idea? self advertising? [m8 i r8 8](http://forum.kerbalspaceprogram.com/index.php?/topic/134360-10232016-12-v051-revamped-stock-solar-system/&do=findComment&comment=2971338)?

let me know :D

**Comment by StollD** [comment]
https://github.com/Kopernicus/kittopia-dumps
