### ISSUE TITLE
PQSCity2 Issues

### ISSUE THREAD

**Issue by DerpyFirework** [Sigma88/Sigma-Dimensions#34]
A few weeks ago I mentioned a problem I was having with PQSCity2 and SigmaDimensions, and felt like posting it here as well, so you can keep track of it. I hope you don't mind.

The issue is with PQSCity2 (And possibly PQSCity) objects with snapToSurface set to false, and this results in them being repositioned several hundred kilometers above their intended position by SigmaDimensions.
(ie 600km above the intended point at 2x scale)

I believe the code in question starts at line 108 in SigmaDimensions.cs and appears to set the alt value of the PQSCity2 to account for the planet being rescaled, but it would seem PQSCity2 accounts for it already.

If you need any more information, I'll be happy to provide it.

edit: Just tested without the .dll, and everything's in the right place (other than KSC), and the planet is still scaled up.

I think treating pqsCity2.alt the same way as pqsCity2.snapHeightOffset might fix it, but then again, I know almost nothing about this.

**Comment by Sigma88** [comment]
I'm a bit busy lately so I haven't had time to check on it yet, thanks for opening an issue, it will help me keep track of this stuff

**Comment by Sigma88** [comment]
could you please give me a link to download your mod? so that I can test my dll against non-stock PQSCity2 mods?

thanks

**Comment by DerpyFirework** [comment]
[https://github.com/DerpyFirework/KSP-Structures](url)
The GameData folder contains the compiled DLL and there is an example.cfg with an example object, however the example object is not affected by the bug I described above.

Thanks for looking into this!

**Comment by DerpyFirework** [comment]
Here's a config that places the example.cfg in the water next to KSC, will get the issue when used with a SigmaDimensions configs with resize anything but 1
[example.txt](https://github.com/Sigma88/Sigma-Dimensions/files/902742/example.txt)

**Comment by Sigma88** [comment]
perfect thanks! I'll take a look tonight

**Comment by Sigma88** [comment]
I've fixed this issue, I forgot to compile the dll but I should be able to upload a test version here tonight

the fix has already been pushed to the development branch, so if you know how to compile it yourself feel free to test it

I suggest using [this version](https://github.com/Sigma88/Sigma-Dimensions/tree/b5aefeb29fa7cfa52f442f9abe8e79e0d6c281e2) since the later changes haven't been tested yet

**Comment by DerpyFirework** [comment]
Managed to compile it, and the fix works perfectly! Thank you for looking into this.

**Comment by Sigma88** [comment]
no problem!

happy it worked :)

**Comment by Sigma88** [comment]
I'm going to close this issue, feel free to reopen it if you feel like there are still issues
(or make new ones for new issues)
