### ISSUE TITLE
scatterer compatibility

### ISSUE THREAD

**Issue by Sigma88** [Sigma88/Sigma-Dimensions#47]
@Galileo88 I am working to add scatterer compatibility to SD

could you test out this version of SD? [link](https://github.com/Sigma88/Sigma-Dimensions/files/1254600/SigmaDimensions.scatterer.dev.version.zip)

this version should do automatically what you define [here](https://github.com/Galileo88/Rescale/blob/master/RESCALE_10/10xKSP.cfg#L188-L202)

it also adds an option to bypass the "Rescale" parameter by adding a "customRescale" inside the star node (in case you need a different rescale factor)

**Comment by Sigma88** [comment]
I've found a couple of issues, this one should be better:

[link](https://github.com/Sigma88/Sigma-Dimensions/files/1254620/SigmaDimensions.scatterer.dev.version2.zip)

**Comment by Poodmund** [comment]
Scatterer does rescale some parameters automatically if it detects that the values are unsuitable for the body they are being applied to. This is how you can apply Kerbin's configs to, say, Duna and they'll still look suitably sized. It's probably wise to get @LGhassen's input on these cases.

**Comment by Sigma88** [comment]
the only thing I did was translate into a plugin what galileo had done in the cfgs for Rescale!

I guess those modifications are required, otherwise he would not have added to the cfg (I suppose)

**Comment by LGhassen** [comment]
Scatterer rescales atmos automatically based on your planet's radius.

Is there anything you had to modify manually or that needs changes in sigma dimensions?

**Comment by Sigma88** [comment]
@LGhassen I'm not very familiar with scatterer.

what galileo currently changes in his cfgs is this:


		@flareSettings[2] /= #$@SigmaDimensions/Rescale$
		@spikesSettings[2] /= #$@SigmaDimensions/Rescale$
		@sunGlareFadeDistance *= #$@SigmaDimensions/Rescale$

so, basically, he divides the third element of "flareSettings" and "spikesSettings" by the Rescale parameter (which is a multiplier for orbits)


so in a 10x system, those values will be divided by 10


while he multiplies "sunGlareFadeDistance" by the Rescale parameter


I had to write a plugin to edit those parameter because they are not accessible via MM

**Comment by Sigma88** [comment]
@galileo88 @Poodmund  if any of you could test this version of SD I can use your opinion

I have no idea what the intended result must look like so I might miss something when taking a look

**Comment by LGhassen** [comment]
Yes, it makes sense, the values used in scatterer are inverses.

**Comment by Sigma88** [comment]
as far as I can tell this should be solved
