### ISSUE TITLE
Could you make a version of the real solar system that magnifies the original planet?

### ISSUE THREAD

**Issue by ClearPlume** [Sigma88/Sigma-Dimensions#49]
I am so sorry to ask you so that the steps you say are really detailed...

I just can not understand them...My English is too bad...(T^T)

I write what you say(I must have made a mistake), but it does not take effect. T_T

**Comment by Sigma88** [comment]
if you are interested in a version of the Stock KSP system resized to the same size as the Real Solar System I would suggest you to install the 10.625x config from [Rescale!](https://forum.kerbalspaceprogram.com/index.php?/topic/163965-0/)

this is the easiest way to use SigmaDimensions if you are not sure how to choose the settings
