### ISSUE TITLE
Separating a static from a group for KK

### ISSUE THREAD

**Issue by eberkain** [Sigma88/Sigma-Dimensions#57]
# NOTE

**KK now handles the altitude by itself**

This means that now SD will not move those statics as long as you install KKtoSD alongisde KK and  SD

<br>

# Original Issue

I'm testing with 1.3.1 and the base mods for KK, SD, SVT and your KKtoSD mod.  Looking to make KerbinSide work with RESCALE! 3.2x.   I'm hoping to get all the bases working in the rescale and fix any floating buildings problems.  I've made alot of progress to getting it done, but am having an issue as described below.   

This code was posted in the forum thread as a fix for the floating radar tower near KSC. 

```
PQSCity_Groups
{
    GROUP
    {
		name = KSCUpgrades2
		body = Kerbin
		
		MODS
		{
		PQSCity = KSCUpgrades_ksideradar3_0
		}
    }
}
```

It works perfect and from my understanding this is creating a new group called KSCUpgrades2 and giving it one static.  Since no center is defined then the first static in the group is used as the center.  This has the effect of moving the tower back to the hilltop because the lon/lat of the terrain feature is the same.  
 
This code does not work however.  
```
PQSCity_Groups
{
   GROUP
    {
		name = DeadkerbalPit2
		body = Kerbin

		MODS
		{
			PQSCity = DeadkerbalPit_ksidecontroltower4_0
		}

    }	
}
```
Looking at the static definition for both the floating radar towers I can not figure out why one works and the other does not.  Literally the only difference I see is how the parent group is defined.  KSCUpgrades uses CentralPQSCity = KSC and DeadkerbalPit is using CentralLAT and CentralLON

**Comment by Sigma88** [comment]
hi, first of all you need to make sure that the name `DeadkerbalPit_ksidecontroltower4_0` is the correct name for the specific static you want to edit.

you need to install [kittopia](https://github.com/Kopernicus/KittopiaTech/latest) and run the game as usual

once in game, hit \[CTRL\] + \[P\] , select the correct planet, go to the PQS tab and look for the static you want to exclude from the group

between the informations on that static you should find a `name`, this is what you want to use in your cfg.

make sure it's called `DeadkerbalPit_ksidecontroltower4_0` otherwise take note of the correct name and change your cfg accordingly


if this still doesn't work, I will need you to upload some files.

[here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-131-kopernicus-release-3-nov-30/&page=27#comment-2793409) you can find the list of all informations I might need to debug this issue

I will also need a link to the mod that adds that particular static you are trying to affect

**Comment by eberkain** [comment]
You got it, I had the wrong name.   Thank you for pointing me to kittopia, I had not seen it before. 

The other thing I need to figure out how to get to work is moving just a single static in a group up or down without changing its lon/lat position relative to the other nearby statics.  

I feel like this should work...  

```
	GROUP
    {
		name = DeadkerbalPit3
		body = Kerbin
		
		CENTER 
		{
			CentralPQSCity = DeadkerbalPit
		}
		MODS
		{
			PQSCity = DeadkerbalPit_ksidemountaindoors2_0
			PQSCity = DeadkerbalPit_ksidecawler1_0
		}
        MOVE
        {
            fixAltitude = -30
        }
    }

```

But that does not seem to do anything.    So I tried it without specifying the center.  That moved those two buildings off a ways, back to the first ones original lon/lat im assuming.    So them I tried this...
  
```
	GROUP
	{
		name = DeadkerbalPit
		body = Kerbin
		CENTER 
		{
			CentralLON = -127.7
			CentralLAT = 14.68
		}
		//looks good
	}	
	//lower the mountian door and crawler because its clipping with the launch spawn
	GROUP
    {
		name = DeadkerbalPit3
		body = Kerbin
		
		CENTER 
		{
			CentralLON = -127.7
			CentralLAT = 14.68
		}
		MODS
		{
			PQSCity = DeadkerbalPit_ksidemountaindoors2_0
			PQSCity = DeadkerbalPit_ksidecawler1_0
		}
        MOVE
        {
            fixAltitude = -30
        }
    }
```
But that somehow makes everything in the DeadkerbalPit group lower, not just those two buildings.

**Comment by Sigma88** [comment]
>You got it, I had the wrong name. Thank you for pointing me to kittopia, I had not seen it before.

glad you solved your problem!

>The other thing I need to figure out how to get to work is moving just a single static in a group up or down without changing its lon/lat position relative to the other nearby statics.

it is not possible to change the position of just one single building, you will need to create a new group with a different name, with the same center as the original group, but with a different "MOVE" node

like you do in your second example.
you say that everything is moved which is weird. I will take a look to see what's going on.


btw, in your first example `CentralPQSCity = DeadkerbalPit` still needs to use the proper name of one of the PQSCity.

**Comment by eberkain** [comment]
Ok, so I checked kittopia looking for just a DeadkerbalPit PQSCity, and there is one called "Deadkerbal Pit".  So I tried using that to set the center as the CentralPQSCity = .   Its underground, but It no longer has the issue where the buildings were clipping together oddly, which is why I was trying to move individual buildings in the first place.  

using LON/LAT settings i get this https://i.imgur.com/NEH00Ua.png
using the CentralPQSCity i get this  https://i.imgur.com/A2Oftw6.png

Ignore that one is underground and look at the building arrangement, its just a little different.  

Unless I come across another weird one, I think I will be able to finish the configs, just will have to set the fixAltitude for all of them.  Is it safe to move an object with kittopia to figure out what that offset needs to be?  are the changes saved in the save file so starting a new game will revert it, or is it changing the source files?

**Comment by Sigma88** [comment]
what version of SD are you running on?
the antenna in the background should not be floating if you are using the latest SD

**Comment by eberkain** [comment]
This is what my log shows for all the loaded DLLs
ModuleManager v3.0.1.0
CustomAsteroids v1.5.0.0
Atmosphere v1.2.2.1
CelestialShadows v1.2.2.1
CityLights v1.2.2.1
EVEManager v1.2.2.1
PartFX v1.2.2.1
PQSManager v1.2.2.1
ShaderLoader v1.2.2.1
Terrain v1.2.2.1
TextureConfig v1.2.2.1
Utils v1.2.2.1
_BuildManager v1.2.2.1
KerbalKonstructs v2.0.0.0 / v1.2.0.1
Kopernicus.OnDemand v1.0.0.0
ModularFlightIntegrator v1.0.0.0 / v1.2.4.0
Kopernicus.Components v1.0.0.0
Kopernicus.Parser v1.0.0.0
Kopernicus v1.0.0.0
KittopiaTech v1.0.6479.31186
SigmaDimensions v1.0.0.0
KKtoSD v1.0.0.0
Kopernicus.Parser v1.0.0.0
Kronometer v1.0.0.0
Sigma88LoadingScreens v0.3.1.0
SigmaBinary v1.0.0.0
Sigma88LoadingScreens v0.3.1.0

**Comment by Sigma88** [comment]
I can't really see the version from that.

I would need the files listed [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-131-kopernicus-release-3-nov-30/&page=27#comment-2793409)

**Comment by eberkain** [comment]
https://drive.google.com/open?id=1UcdEAxf84VF_GuC04FjiGHqJ9a7zAWU8

**Comment by eberkain** [comment]
Sorry for being such a pain and not following instructions for the first time.  Thank you for taking a look at whats going on and helping me figure this out.   My goal is to play a 3.2 rescale with the stock system + OPM and use KK + KerbinSide to have all those launch points.  

I have collected everything you asked for and its here.  https://drive.google.com/open?id=15IKSJW20RnahurtnByy5tI-HTGLkp-B6

**Comment by Sigma88** [comment]
don't worry, I'll take a look at your files when I have some spare time 👍 

could you also link me to the dewnload page of the version of kerbinside you are using? so that I can test it on my pc

**Comment by eberkain** [comment]
version 1.4 from here  https://spacedock.info/mod/1347/Kerbin-Side%20Complete%20continued

**Comment by Sigma88** [comment]
the main problem with DeadKerbalPit seems to be that the antenna (circled in red in the pic) is included in the group. since it's the first static of the group uses that antenna as the "center" of the group, which means the rest of the buildings are moved inside the ground.

the majority of the issues can be solved by removing that antenna from the group.

this is what it looks like on 3.2x with the antenna group changed:

![image](https://user-images.githubusercontent.com/12640834/35040220-9ddb2240-fb80-11e7-887e-b0b97b5f6a90.png)

as you can see, the buildings are still floating a bit (green circle), so you might want to correct the altitude using a cfg, you might also want to remove the building in the yellow circle from the group, otherwise it will be moved down with the other buildings and disappear inside the ground

**Comment by Sigma88** [comment]
actually, this cfg will fix the altitude issue and also put the buildings in a better position

keep in mind that you will still need to change the group of the tower and the antenna (yellow and red circles from the prev image)

```
PQSCity_Groups
{
	GROUP
	{
		name = DeadkerbalPit
		body = Kerbin
		CENTER
		{
			CentralPQSCity = DeadkerbalPit_ksidemountaindoors2_0
		}
	}
}
```

pic:
![image](https://user-images.githubusercontent.com/12640834/35040604-094f2e94-fb82-11e7-8a91-0b41d04d8313.png)

**Comment by Sigma88** [comment]
for the tower I suggest something like this:

```
PQSCity_Groups
{
	GROUP
	{
		name = DeadkerbalPit_Tower
		body = Kerbin
		CENTER
		{
			CentralPQSCity = DeadkerbalPit_ksidemountaindoors2_0
		}
		MODS
		{
			PQSCity = ################ (name of the tower)
		}
		MOVE
		{
			fixAltitude = ######### (desired offset)
		}
	}
}
```

for the antenna you just need this instead:
```
PQSCity_Groups
{
	GROUP
	{
		name = DeadkerbalPit_Antenna
		body = Kerbin
		MODS
		{
			PQSCity = ############## (name of the antenna, it might be a PQCity2 I am not sure)
		}
	}
}
```

**Comment by eberkain** [comment]
The issue im having is that the mountian door model is clipping through the launchpad and alot of times when you try to use it, the craft just explodes.   

With this config

```
	GROUP
	{
		name = DeadkerbalPit
		body = Kerbin
		CENTER 
		{
			CentralPQSCity = DeadkerbalPit_ksidemountaindoors2_0
		}
	}	
	//fix the floating radar tower
    GROUP
    {
		name = DeadkerbalPit2
		body = Kerbin
		
		MODS
		{
			PQSCity = DeadkerbalPit_ksidetrackingdish11_0
		}
    }
	//fix the control tower  
    GROUP
    {
		name = DeadkerbalPit3
		body = Kerbin
		
		MODS
		{
			PQSCity = DeadkerbalPit_ksidecontroltower4_0
		}
    }	
```

I get this result...   https://i.imgur.com/vxRHoMn.png

which is bad because it has the ramp for the mountian door model more than half covering the launch pad.  So I either need a way to raise the launch pad, lower the mountian door, or move them farther apart, while also retaining their adjusted relative starting positions.

**Comment by Sigma88** [comment]
yes I see what you mean now, I need to check a couple of things in the code to understand what is going wrong. the position of each piece relative to each other should not change if the code works correctly, but this is definitely not the case here it would seem

**Comment by Sigma88** [comment]
the antenna and the tower will always need to be fixed separately, but the launchpad should not have a different position compared to the doors, so that's something I will try to fix in SD code

**Comment by eberkain** [comment]
this seems to be ok, the launch pad is clear if you use "Deadkerbal Pit" as the central point.  
```
	GROUP
	{
		name = DeadkerbalPit
		body = Kerbin
		CENTER 
		{
			CentralPQSCity = Deadkerbal Pit
		}
        MOVE
        {
            fixAltitude = -60
        }		
	}
```

I've nearly gotten them all done now.  The biggest problem is Ben Bay.  https://i.imgur.com/KIvpm21.png
There are 17 different statics spread around this coastal area in a few little clusters, I've got a list of all the names but no idea which goes with which.  I wish I could mouse over or click on a static to see its PQSCity name.

**Comment by Sigma88** [comment]
> I wish I could mouse over or click on a static to see its PQSCity name.

I think you can do that with [DebugStuff](https://forum.kerbalspaceprogram.com/index.php?/topic/135726-12-debugstuff-2016-10-25-see-the-hidden-secrets-of-the-game-objects/)

**Comment by eberkain** [comment]
I think BenBay may just be on the chopping block.   :)

**Comment by eberkain** [comment]
whoops, that was the wrong button.  :)

**Comment by eberkain** [comment]
I'm down to just a couple left to finish.  I did get Ben Bay sorted.  However I cannot get LodnieIsles to do anything.  I've quadruple checked and the KK group name is LodnieIsles and I've tried to assign a center every way I can think of and it never does anything, (acting like I have the wrong group name).  I even tried making a new group that included every static in that KK group individually, and that even does nothing.   Could these statics be flagged in some way that prevents them from being moved?  If so is that something that can be MM patched?

You can see the current state of the config here.  https://drive.google.com/open?id=1vqMUb4fgm9wvTGn4me2FKoVTXxU53F9Y  

I feel like I have a good handle on how it works now, but this one group just does nothing for me nad is really working my nerves tonight.

**Comment by Sigma88** [comment]
There shouldn't be any unmovable statics, I'll take a look

**Comment by Sigma88** [comment]
to get the LodnieIsles group to reposition correctly you need to exclude the ground control antenna

the one defined in the cfg at `GameData\KerbinSide\GroundControl\LodnieIsles\ksidetrackingdish11.cfg`

if you do that the rest of the buildings are repositioned correctly, you might still need to fix the altiude

**Comment by eberkain** [comment]
I tried a number of different things this morning.  

```
		GROUP
	{
		name = LodnieIsles
		body = Kerbin

		CENTER
		{
			CentralPQSCity = Lodnie Isles

		}
	}
	//fix the radar   
    GROUP
    {
		name = LodnieIsles2
		body = Kerbin
		
		MODS
		{
			PQSCity = LodnieIsles_ksidetrackingdish11_0
		}
    }		

```
result -> https://i.imgur.com/qoWT2MQ.png

```
	GROUP
	{
		name = LodnieIsles
		body = Kerbin

		CENTER
		{
			CentralLON = 14.200
			CentralLAT = 29.740
		}
	}
	//fix the radar   
    GROUP
    {
		name = LodnieIsles2
		body = Kerbin
		
		MODS
		{
			PQSCity = LodnieIsles_ksidetrackingdish11_0
		}
    }		

```
result -> https://i.imgur.com/VeOganJ.png


```
	GROUP
	{
		name = MyLodnieIsles
		body = Kerbin

		MODS
		{
			PQSCity = Lodnie Isles
			PQSCity = LodnieIsles_ksideapproachlights_0
			PQSCity = LodnieIsles_ksidebarracks3_0
			PQSCity = LodnieIsles_ksidecontroltower4_0
			PQSCity = LodnieIsles_ksidedetached1_0
			PQSCity = LodnieIsles_ksidedetached1_1
			PQSCity = LodnieIsles_ksidefueltanks3_0
			PQSCity = LodnieIsles_ksidefueltanks3_1
			PQSCity = LodnieIsles_ksidefueltanks3_2
			PQSCity = LodnieIsles_ksidehangar2_0
			PQSCity = LodnieIsles_ksidehangar2_1
			PQSCity = LodnieIsles_ksidehangar2_2
			PQSCity = LodnieIsles_ksidehangars1_0
			PQSCity = LodnieIsles_kshelipadbasic_0
			PQSCity = LodnieIsles_ksideofficeestate1_0
			PQSCity = LodnieIsles_ksideofficeestate3_0
			PQSCity = LodnieIsles_ksideradardish_0
			PQSCity = LodnieIsles_ksidetaxiway2_0
			PQSCity = LodnieIsles_ksidewatertower_0
		}
	}
	//fix the radar   
    GROUP
    {
		name = MyLodnieIsles2
		body = Kerbin
		
		MODS
		{
			PQSCity = LodnieIsles_ksidetrackingdish11_0
		}
    }	
```
result -> https://i.imgur.com/GFWvm0a.png


Based on my experience doing all the other bases, any of these methods should do something, but the buildings just sit there doing nothing, taunting me.

**Comment by eberkain** [comment]
I'm down to 4 bases left and they are all acting this same way.  KrakensBelly LodnieIsles KSC2 RoundRange

Which really is confusing, because I know KSC2 was working at some point, and i skipped over it cause it seemed to have so many issues.  

I'm creating a new save every time i check in game, and even tried clearing out the MM cache, but nothing seems to make a difference.  

I think I'm going to setup a clean install with only the couple mods needed for this and see if somehow something is interfering.

**Comment by Sigma88** [comment]
this cfg did the trick for me

```
PQSCity_Groups
{
	GROUP
	{
		name = LodnieIsles2
		body = Kerbin
		
		MODS
		{
			PQSCity = LodnieIsles_ksidetrackingdish11_0
		}
	}
	GROUP
	{
		name = LodnieIsles
		body = Kerbin
		
		CENTER
		{
			CentralPQSCity = LodnieIsles_ksidetaxiway2_0
		}
	}
}
```

**Comment by eberkain** [comment]
I put that into my config and it didn't do anything.   So I tried it in a seperate file and removed my config, it worked.  So I split all my groups off into their own files.  Tried it and it didn't work....  So I've got something in one my my configs that is jacking things up for other configs.  The only thing I can think is to start from scratch, adding them in one at a time and checking until I find one that breaks the LodnieIsles group.     //comments are safe anywhere in a config right?

**Comment by Sigma88** [comment]
> //comments are safe anywhere in a config right?

not everywhere-everywhere, but mostly yes

just don't put them between a node and it's brackets

```
EXAMPLE
{
    // here
    CORRECT
    {
        // or here
    }


   WRONG
    // here
    {
    }
}
```

**Comment by eberkain** [comment]
So, I binary searched down and found the problem config, if I load everything but the config for KKVLA then the LondieIsles config works.   KKVLA (below) is long, but nothing looks wrong to me.  I wasn't really happy with it anyhow so I'll try a different approach.  Its a tough once because they have train tracks and getting those to look any kind of way decent is next to impossible.  

```
PQSCity_Groups
{

	//=====================================================================
	//		KKVLA  &  AREA 110011 - READY!
	//=====================================================================
	GROUP
	{
		name = KKVLA
		body = Kerbin
		CENTER 
		{
			CentralPQSCity = KKVLA_ksiderailbridge_0
		}
        MOVE
        {
            fixAltitude = -10
        }
	}
    GROUP
    {
		name = KKVLA2
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidehangars1_0
			PQSCity = Area 110011
			PQSCity = KKVLA_kside110011lift_0
			PQSCity = KKVLA_ksideobservatory1_0
			PQSCity = KKVLA_ksidemountaindoors_0
			PQSCity = KKVLA_ksidemountaindoors_1
			PQSCity = KKVLA_ksidearcology_0
			PQSCity = KKVLA_ksidetanks13_0
			PQSCity = KKVLA_ksidevabsph1_0
		}
    }	
    GROUP
    {
		name = KKVLA3
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA
		}
    }	
    GROUP
    {
		name = KKVLA_0
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_0
		}
    }	
    GROUP
    {
		name = KKVLA_1
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_1
		}
    }	
    GROUP
    {
		name = KKVLA_2
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_2
		}
    }	
    GROUP
    {
		name = KKVLA_3
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_3
		}
    }	
    GROUP
    {
		name = KKVLA_4
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_4
		}
    }	
    GROUP
    {
		name = KKVLA_5
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_5
		}
    }	
    GROUP
    {
		name = KKVLA_6
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_6
		}
    }	
    GROUP
    {
		name = KKVLA_7
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_7
		}
    }	
    GROUP
    {
		name = KKVLA_8
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_8
		}
    }	
    GROUP
    {
		name = KKVLA_9
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish2_9
		}
    }	
    GROUP
    {
		name = KKVLA_10
		body = Kerbin
		
		MODS
		{
			PQSCity = KKVLA_ksidekkvladish1_0
		}
    }	
```

**Comment by eberkain** [comment]
KKVLA_ksidekkvladish1_0 was a bad name, fixing that seems to have fixed the problem with the other configs... dont ask me.

**Comment by eberkain** [comment]
I think I have all the configs done now, thank you so much for the help!

**Comment by Sigma88** [comment]
No problem!

**Comment by Sigma88** [comment]
I saw you are looking for the old ksc lat/lon

You don't need those coords. You can use CentralPQSCity like you do for KSC

You just need to find the name of the old ksc

Same goes for ksc2, which is named "KSC2"

**Comment by eberkain** [comment]
What could I do about these?  https://i.imgur.com/tmaxrCo.png
I'm pretty sure the floating radar dish is one of the stock CommNetDish, and there are multiple with the same name.

**Comment by Sigma88** [comment]
no that's not a stock one

that is probably from the "GroundControl" folder in KerbinSide

if you install DebugStuff you should be able to get the name via mouseover

**Comment by eberkain** [comment]
Is there a way to adjust spawn points for some of the pads? 
https://i.imgur.com/iVaXh7f.png

**Comment by Sigma88** [comment]
as far as I know the spawn point is hardcoded inside the model

you may have some luck asking the KK dev

**Comment by eberkain** [comment]
ok, thanks

**Comment by theonegalen** [comment]
Hi, @sigma88, I'm trying to make KktoSD configs for the SM_Statics mod, and the problem I'm running into is that multiple instances of the same static have the same name in KittopiaTech, so I don't know which one to use as the center, or exclude from the old groups.

**Comment by Sigma88** [comment]
KK should automatically generate different names, I don't think SD has the ability to distinguish between statics with the same name

I'll go back and take a look at the code, but I'm 90% positive this will require different names for the statics

**Comment by theonegalen** [comment]
So maybe I should rename some things and send spanner a pull request.

**Comment by Sigma88** [comment]
@GER-Space didn't KK used to name statics so that every added PQSCity had a different name?

**Comment by GER-Space** [comment]
they should be named by <groupname>_<modelname>_<occurance of the model in group> 
the lone exception are launchsites which need to be named diffrently, because of some KSP internal black magic. (I'm still need to figure out why)
I cannot imagine a reason why the names should not be unique

**Comment by theonegalen** [comment]
So, it turns out that when I changed the group of the SM_statics from KSCUpgrade to KSCUpgrade_SM, some of the boats ended up with the same name. When I changed the group back to KSCUpgrade, they had individual names again.

**Comment by theonegalen** [comment]
Also, when working with the BADT airfields and arenas Statics, whenever I set the central pqs group to anything besides a launch site, they would be scattered across the landscape. Which makes it impossible to actually line up most of those airfields.

**Comment by theonegalen** [comment]
Sure. I mostly gave up in frustration yesterday, but I can do that later tonight.

Have you decided what you're going to do about SD, etc, for 1.4?

**Comment by Sigma88** [comment]
I don't have an ETA for compatibility of any of my mods and ksp1.4 sorry
