### ISSUE TITLE
Is there any plans for 1.4.x or 1.4.2 support?

### ISSUE THREAD

**Issue by Iso-Polaris** [Sigma88/Sigma-Dimensions#64]
There's just no way I can play with a stock-size KSP.
SD is just the one mod I would always appreciate.
The game is dead for me without SD

**Comment by Sigma88** [comment]
I have plenty of plans 😀 

what's missing is the free time to do them all 😃 

sadly I can't give you an ETA, in the meantime, if you test the mod on 1.4.2 and provide some bug reports, that might help me speed up the process of updating.

if you want to see how to make a complete bug report you can read [this](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-142-kopernicus-release-1-march-30/&page=27#comment-2793409)

**Comment by Sigma88** [comment]
I've recompiled SD against ksp 1.4.3 and kopernicus 1.4.3-1

I haven't tested it, so if you have problems feel free to open a new issue
