### ISSUE TITLE
Engine shrouds misaligned with Making History and 6.4 rescale

### ISSUE THREAD

**Issue by Wuzetek** [Sigma88/Sigma-Dimensions#70]
Reproduce:
1) fresh 1.4.3. install
2) install Making History (without it everything seems to be ok)
3) install Kopernicus and Sigma Dimensions 0.10.1
4) set 6.4 resize and rescale (without rescale everything seems to be ok).
5) create new vessel with engine shroud.

https://imgur.com/g7HaNaL

**Comment by Sigma88** [comment]
SD does not affect vessels so I don't really know what could be going on there

I'll look int it

**Comment by Sigma88** [comment]
can you try using some clamps to keep the vessel elevated?

**Comment by Wuzetek** [comment]
Yeah, I tried with clamps:
https://imgur.com/16cGJNo
I also tried using struts and Kerbal Joint Reinf - no changes. As I said, it is fresh install, just 1.4.3+MH+SG. 
Game Data Folder:
https://imgur.com/qnGeMpG

**Comment by Sigma88** [comment]
I'll look into it, but I have no idea where to start from since my mod never does anything to parts / vessels

**Comment by Sigma88** [comment]
can you send me the craft file you are using?

**Comment by Galileo88** [comment]
@Wuzetek this is a stock issue. I have confirmed this myself. It is definitely exaggerated by rescaling the bodies, but the issue is not with SD

Here are images from a completely stock game:
[HERE](https://i.imgur.com/1GL78up.png) and [HERE](https://i.imgur.com/rEPCu78.png)

**Comment by Sigma88** [comment]
@Galileo88  nice find, thank you!

**Comment by Wuzetek** [comment]
Oh, thank you!
