### ISSUE TITLE
ModuleManager error on load

### ISSUE THREAD

**Issue by TykoTek** [Sigma88/Sigma-Dimensions#71]
This message pops up during game launch:

1 error related to GameData/Dimensions/Configs/ReDimension/newCacheFiles.cfg

Here are my log files: https://www.dropbox.com/sh/3ahnlcciy0ltcsd/AAAwJ2fKzCG7vj-BqOM5aGLra?dl=0

**Comment by Sigma88** [comment]
apparently you have a body without a name, this will cause all kinds of errors with kopernicus as well

```
[ModuleManager] Cannot find key name in Body
```

you should be able to find out which body is the nameless one by removing SD and then looking at the module manager cachefile

after that, you should find which is the mod that creates a body without a name and fix that


once all bodies have a name, SD will stop giving errors

**Comment by TykoTek** [comment]
Thanks! Interestingly I rolled back to 0.9.8 and the problem disappeared. I'm only running GPP which has always been pretty bug free. I am running a pre-release of ReScale, but I didn't think that would change the body names and such.

Appreciate the quick reply.

**Comment by Sigma88** [comment]
I'll close the issue since it seems to be solved, let me know if you still have problems with it
