### ISSUE TITLE
FPS Issue when Sigma-Dimensions installed

### ISSUE THREAD

**Issue by Joker58th** [Sigma88/Sigma-Dimensions#72]
Hi Sigma88, in trying to come up with a modded 1.3.1 install in which to start a new career and I came across some performance issues that when narrowed down seem to point towards Dimensions.

I understand that there could be other factors in the modded install that contribute to the fps drop so I guess I am asking about the clean install that drops from 244 to 166 fps.  Is that normal for dimensions to behave like this?

As you can see from the pictures, the modded install drops from 203 to 40 fps.  The only thing I'm doing is adding or removing Dimensions for each of these tests.

Also notice the GPU seems to be limited some how when Dimensions is installed.

[Pictures](https://imgur.com/a/BpCtFBn)

**Comment by Gordon-Dry** [comment]
@Joker58th I also had the suspicion that Sigma Dimensions hits the performance.

I just will do a test next session, which is simple because I only used SigDim for 10x ReScale, no other parameters changed.

I will try it with this config:
GameData\zFinal\zzz_10xRescaleWithoutSigmaDimensions.cfg
```
@PART:FOR[zzz_10xRescaleWithoutSigmaDimensions]
{
	@MODULE:HAS[#name[ModuleDataTransmitter]]
	{
        	@antennaPower *= 10
    	}
}

@CUSTOMBARNKIT:FOR[zzz_10xRescaleWithoutSigmaDimensions]
{
	@TRACKING
	{
		@DSNRange[*] *= 10
	}
}

@Kopernicus:FOR[zzz_10xRescaleWithoutSigmaDimensions]
{
	@Body,*
	{
		@Properties
		{
			@ScienceValues
			{
				@spaceAltitudeThreshold *= 10
			}
		}
		@Orbit
		{
			@semiMajorAxis *= 10
		}
		@PostSpawnOrbit
		{
			@semiMajorAxis *= 10
		}
	}
}

@Kopernicus:FOR[zzz_10xRescaleWithoutSigmaDimensions]
{
	@Asteroid,*
	{
		@Locations,*
		{
			@Around,*
			{
				@Body,*
				{
					@semiMajorAxis,*
					{
						@minValue,* *= 10
						@maxValue,* *= 10
					}
				}
			}
			@Nearby,*
			{
				@Body,*
				{
					@semiMajorAxis,*
					{
						@minValue,* *= 10
						@maxValue,* *= 10
					}
				}
			}
		}
	}
}

```

**Comment by Sigma88** [comment]
Can you try to reproduce this issue with a very small rescale? Like 1.1x?

**Comment by Sigma88** [comment]
I think this might be related to the fact that on a bigger planet KSP will try to load more land leading to much more calculations

Not sure tho

**Comment by Joker58th** [comment]
I would be happy to, however, I need to understand how to make a config for that size.  I only use CKAN or manual installs and do not have much experience with MM configs.  Is it as simple as copying an existing config and changing the values to 3.2 to 1.1 for example?  Or is there more to it than that?

**Comment by Sigma88** [comment]
I'll provide you with one as soon as I have time :+1:

**Comment by Sigma88** [comment]
```
@SigmaDimensions
{
    @Rescale = 1.1
    @Resize = 1.1
}
```

this should be enough

**Comment by Sigma88** [comment]
if you could also add the output_log.txt that might help me pinpoint the issue

**Comment by Joker58th** [comment]
I tried 1.1, 21.1 scale and also opengl and get the same results.  Oddly, I tested on a different machine with a lower end video card and could not reproduce the issue.  The frame rates never got over 70 on this machine but it also didn't dip down at all, even with all 100 mods installed.  I'm not sure what to think now.

Here is the log but I got it from KSP_x64_Data.  The path you gave me only had an old log from a month ago.  Maybe from a different install.

[output_log.txt](https://github.com/Sigma88/Sigma-Dimensions/files/2029216/output_log.txt)

**Comment by Sigma88** [comment]
I have no idea what could be the cause of this issue.

you could try installing SD but not changing the size of the planet, to see if that has any effect.

but the logs are clean, and nobody else reported this bug, so it might as well be a rare situation that occurs on your machine that causes SD to behave in that way and that I have no way to reproduce myself

**Comment by Joker58th** [comment]
Yeah, I agree, seems to be something wonky going on here on my end.  Just for the record, my machine specs are i7-2600K overclocked to 5Ghz, 16GB ram, GTX 1060 6GB in case this ever comes up again.

Also, the tests I did initially were just adding or removing dimensions with no scaling.  Kopernicus and MFI get installed as dependencies but that is it.

Thanks for your time.  I appreciate it.

**Comment by Gordon-Dry** [comment]
I read that Trajectories triggers this:
Removed it and issue is gone.
