### ISSUE TITLE
Sigma Dimensions loading screens in GPP install

### ISSUE THREAD

**Issue by EndIris** [Sigma88/Sigma-Dimensions#74]
It isn't particularly important, but when playing with SigmaDim and GPP, both of their loading screens show up. The SigmaDim loading screens kind of clash with the oil painting styles of GPP's, and they also show the stock planets which don't exist in GPP. I have fixed it in my own install by deleting the pictures, but I think there is probably some code which could be written to detect GPP and hide the SigmaDim loading screens if it is found.

**Comment by Sigma88** [comment]
I won't "autodetect" GPP but I might look into an option to stop loading screens from other mods to load
