### ISSUE TITLE
Offer to help test.

### ISSUE THREAD

**Issue by Nightside101010** [Sigma88/Sigma-Dimensions#76]
Hi @Sigma88 , 
I assume that Dimensions is not compatible with the latest Kopernicus.
I'm just popping in to offer help with any testing or config related aspects of this project.
Thanks for your contributions to KSP.

**Comment by Sigma88** [comment]
I apreciate your offer, right now I'm very busy at work, in preparation of my holidays.

I will not have time to touch ksp in august, I am not sure when I will have time to update SD, but if I need help I will ping you here

**Comment by Sigma88** [comment]
this is a bit old so I'm going to close it, however the latest release is out and I didn't do too much testing on it, so if you want to give it a try and find any bugs please let me know
