### ISSUE TITLE
Failed to load Body: Squad/Moho

### ISSUE THREAD

**Issue by Chrono486** [Sigma88/Sigma-Dimensions#82]
[KSP.log](https://github.com/Sigma88/Sigma-Dimensions/files/3293764/KSP.log)

[ModuleManager(configcache).txt](https://github.com/Sigma88/Sigma-Dimensions/files/3293767/ModuleManager.configcache.txt)

[Kopernicus.log](https://github.com/Sigma88/Sigma-Dimensions/files/3293768/Kopernicus.log)

and the Moho log
[Moho.Body.log](https://github.com/Sigma88/Sigma-Dimensions/files/3293769/Moho.Body.log)

I am using KSP 1.7.0
Mod List:
Kopernicus 1.7.0-1
ModularFlightIntegrator 1.2.6
SigmaDimensions 0.10.3
ModuleManager 4.0.2

I had uninstalled KSP through steam, then deleted the entire KSP folder in /Steamapps/common, then reinstalled KSP 1.7.0. I am using the most up to date mod versions I can find for 1.7.0. The game is fully operational with just Kopernicus and its prerequisites. When I add Sigma Dimensions with stock config, I can get to choosing a save file, however It will not stop loading, although it plays the ambient noise for the KSC.

I have little to no knowledge of coding or making mods in general; but I can pick out where I think its going wrong in the kopernicus log (linked above):

[LOG 22:19:32]: [Kopernicus]: Configuration.Loader: Loaded Body: Sun
[LOG 22:19:32]: [Kopernicus]: Configuration.Loader: Failed to load Body: Squad/Moho: Argument cannot be null.
Parameter name: type

A similar few lines are found toward the end of the moho.body log (also linked above). It is worth noting the ModularFlightIntegrator.version file says the maximum ksp version is 1.6.9; but Modularflightintegrator still works without sigma dimensions.

If I missed anything important, I can provide files on request.

**Comment by Sigma88** [comment]
0.10.3 is not going to work with ksp 1.7.0

Try 0.10.2 but that was for 1.6.1 iirc so it might not work as well

**Comment by Chrono486** [comment]
just tried it, 0.10.2 works in KSP 1.7.0. Thank you so much, issue resolved.
