### ISSUE TITLE
"15 errors related to GameData/.../resizePQSMods.cfg"

### ISSUE THREAD

**Issue by maushacks** [Sigma88/Sigma-Dimensions#89]
As the title describes it. 
As you modified the resizePQSMods.cfg file a few days ago, I thought maybe a little bug may have crept inside of it.

KSP.log:
https://gist.github.com/maushacks/4f2c301ce81b3897ec62633395454232

Edit: I tried it with module manager 4.0.3 as well. Same error message.

**Comment by Sigma88** [comment]
ah yes, I see the issue

can you try this one please?

[Sigma-Dimensions.v0.10.6.alpha1.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3722558/Sigma-Dimensions.v0.10.6.alpha1.zip)

**Comment by maushacks** [comment]
I only copied the resizePQSMods.cfg from it. And no error reported! :)

**Comment by Sigma88** [comment]
nice

I'll make an update later today

**Comment by Sigma88** [comment]
# The fix to this issue is now live ([v0.10.6](https://github.com/Sigma88/Sigma-Dimensions/releases/v0.10.6))
