### ISSUE TITLE
Blue Circle Texture Appears in Flight

### ISSUE THREAD

**Issue by FractalCyclone** [Sigma88/Sigma-Dimensions#90]
Hi! 

Been struggling with this issue for a while, not really gameplay intrusive but annoying visual bug/glitch/whatever.

Appears most of the time at the beginning of the launch and will "spawn" multiple times throughout the flight in a new position. Multiple can be spawned at one time but it's hard to get a screenshot of them all in one shot. Happens both when launching from the Runway and Launchpad. 

Happens with and without the KSC Extended/Tundra Space Center mods.

Happens with and without Galileo's ReScale configs being used.

It took me a while to actually narrow it down to it being Sigma Dimensions related?

> [KSP.log](https://github.com/Sigma88/Sigma-Dimensions/files/3771339/KSP.log)

> [error.log](https://github.com/Sigma88/Sigma-Dimensions/files/3771382/error.log)

![screenshot3](https://user-images.githubusercontent.com/56998435/67559782-3b078800-f6df-11e9-8f15-4c4d69d8451a.png)

![screenshot7](https://user-images.githubusercontent.com/56998435/67560426-79ea0d80-f6e0-11e9-8f2b-67f3225ccdb1.png)

![screenshot6](https://user-images.githubusercontent.com/56998435/67559784-3b078800-f6df-11e9-9fe9-4f36e16ca35c.png)

> Mods 
KSP: 1.7.3 (Win64) - Unity: 2017.1.3p1 - OS: Windows 10  (10.0.0) 64bit
ClickThroughBlocker - 0.1.7.2
Toolbar - 1.7.22.2
ToolbarControl - 0.1.8.2
CommunityPartsTitles - 0.5.1
BAM - 1.3.2.6
Chatterer Extended - 0.6.2
Chatterer - 0.9.96.2332
CommNetAntennasExtension - 2.1
CommNetAntennasInfo - 2.1.2
Connected Living Space - 1.2.6.2
CorrectCOL - 1.6.4.4
CrewRandR - 1.1.9.2
Community Terrain Texture Pack - 1.0.4
CustomBarnKit - 1.1.19
AdvancedTextures - 1.7.3
DistantObjectEnhancement - 1.9.1
Easy Vessel Switch - 1.11.7052.36539
EditorExtensionsRedux - 3.3.22
Engine Lighting Relit - 1.6.1.1
Environmental Visual Enhancements - 1.7.3
FShangarExtender - 3.5.5
JanitorsCloset - 0.3.6.1
Kerbal Engineer Redux - 1.1.6
Kerbal Joint Reinforcement - 4.1.15
KerbalKonstructs - 1.7.3.4
**Kopernicus - 1.7.3.2**
**Sigma Dimensions  - 0.10.5 (w/ 0.10.6's resizePQSMods.cfg for the MM error fix)**
**Sigma Binary - 1.7.2**
**ReScale 3.2x - 1.0.2.8**
Kronometer - 1.7.1.1
KSC Extended - 1.1
KSP-AVC Plugin - 1.3.1
LoadingScreenManager - 1.2.5.3
MechJebForAll - 1.3.0.6
ModularFlightIntegrator - 1.2.6
NavBallDockingAlignmentIndicatorCE - 1.0.5
OuterPlanetsMod - 2.2.5
PlanetShine - 0.2.6.1
Precise Node - 1.2.10.3
QuickCursorHider - 1.0.7.2
RealPlume - Stock - 2.0
RemoteTechRedevAntennas - 0.1.1
ReStock - 0.1.4
ReStockPlus - 0.1.4
Ship Effects Continued - 1.0.9.1
ShipManifest - 5.2.1
StationKeeping - 0.2.1.1
Stock Visual Enhancements - 1.4
Stock Visual Terrain - 2.2
TextureReplacer - 3.7
ToadicusToolsContinued - 0.22.3.3
TooManyOrbits - 1.1.5.1
Tracking Station Evolved - 1.0.4.1
TrimIndicators - 0.0.1
Tundra Space Center - 1.1
TweakableEverything - 0.1.26
TweakScale - 2.4.3.9
World Stabilizer - 0.9.5
ZeroMiniAVC - 1.0.6

**Comment by Sigma88** [comment]
you have lot of mods there, I will take a look when I get some time, however it might not be possible to pinpoint what is going on with so many mods installed.

do you think you could reproduce the issue with a smallest number of mods? you can just start a new game to avoid damaging your save.

I've never seen this issue and to be honest I have no idea what those spots could be, do they move or when you find one does it remain in the same place?

and I assume they are objects in the world rather than issues on the UI, correct?

**Comment by Sigma88** [comment]
oh, and in case you are using the latest release, please use this version instead:

https://github.com/Sigma88/Sigma-Dimensions/issues/89#issuecomment-541467898

the latest release has a bug I haven't been able to fix yet

**Comment by FractalCyclone** [comment]
Yeah I cut it down to the 54 from 144 to try and figure out what was causing them Haha, mostly part mods I cut out down to ReStock and the visual/rescale/QoL mods. I will try and cut it down further. I was a bit ancy when I figured out removing SD stopped them form showing up.

I will try and reproduce it with the newest version and minimal mods (I had been using the modsPQS from that newest one to get around the MM issues).

They are static in flight, do not move. Definitely not part of the UI. If they are objects, they are non collidable and only have the texture visible from one direction.

**Comment by FractalCyclone** [comment]
They don't move once they are there, but they can spawn anywhere from my active craft.

**Comment by Sigma88** [comment]
hmmm, do you have ground scatter turned on?

can you try turning ground scatter off and see if they still show up?

**Comment by FractalCyclone** [comment]
I was unable to recreate it with the ground scatter off and minimal mods so far. Im going to throw the whole new version into my big save and disable terrain scatters there and just throw it at the wall so to speak. If not I'll revisit the minimal mod save and thow them back in 1 by 1 until I either recreate it again or settle with having wasted all your time >.<

**Comment by Sigma88** [comment]
I made this to help you with trimming mods [image](https://user-images.githubusercontent.com/12640834/67571701-e7c02480-f734-11e9-9c8c-2eb2f0cdf2b9.png)

all mods in green can probably be removed and they should not affect the bug

all mods in purple I have no idea what they do

all mods in red should be necessary for the bug to show up

mods in orange have a good probability of being involved in the bug

mods in yellow have a good probability of NOT being involved in the bug

**Comment by Sigma88** [comment]
apparently you are not the first to experience this,

take a look at this: https://www.youtube.com/watch?v=uXpxmd7ZNNo

as far as I know this was on a normal size OPM, but I am trying to get in contact with ShadowZone to confirm his modlist

**Comment by FractalCyclone** [comment]
I added the Red Orange and Yellows in, all the green were removed, and all but one purple removed (as it is a dependency of KSC Extended) and I am unable to replicate the issue.

**Comment by Sigma88** [comment]
This is interesting, I didn't expect any of the greens to have anything to do with it

Try adding all purples and see what happens

**Comment by FractalCyclone** [comment]
Adding all the purples didn't replicate it either. Ground scatter on/off didn't change it either.

**Comment by Sigma88** [comment]
I am at a loss then, the only thing I can suggest is to try adding only a few greens at a time and check if the bug presents itself.

**Comment by FractalCyclone** [comment]
I'm able to replicate the bug with this set of mods:

> Community Terrain Texture Pack - 1.0.4
Distant Object Enhancement - 1.9.1.1
Kopernicus Planetary System Modifier - 1.7.3-2
ModularFlightIntegratory - 1.2.6.0
Module Manager - 4.0.3
Outer Planets Mod - 2.2.5
Sigma Dimensions - 0.10.6
Sigma Binary - 1.7.2

Removing either Sigma Binary or Distant Object Enhancement resolves the issue. I think there is some sort of conflict between these two mods (and possibly not Sigma Dimensions >.> my bad)

I'll try narrowing it down even farther.

**Comment by Sigma88** [comment]
Removing opm would also remove sigma binary since there would be no binary system required for sb to load

I think this is probably an issue between doe and sb, you can check that by removing opm and adding the sigma binary example "DunaIke"

**Comment by FractalCyclone** [comment]
I will try that 👍

**Comment by Sigma88** [comment]
For future reference, this is the new issue:
https://github.com/Sigma88/Sigma-Binary/issues/52
